CREATE DATABASE PROJETOPDO;
USE PROJETOPDO;

CREATE TABLE TB_USUARIO(
	ID_US int primary KEY auto_increment,
    NOME_US VARCHAR(100),
    EMAIL_US varchar(100)
);

INSERT INTO TB_USUARIO ( NOME_US, EMAIL_US)
VALUES ( 'ADRIANO', '@ADRIANO'),
	   ( 'WILSON' , '@WILSON'),
       ( 'RAISSA' , '@RAISSA');
       
SELECT * FROM TB_USUARIO;
